#!/usr/bin/env python3
"""
Xournal++ Recording to Video/GIF Converter

This script reads a recording JSON file generated by Xournal++ and
converts it to a video or GIF using Cairo and ffmpeg.

Usage:
    python recording_to_video.py recording.json output.mp4 [--fps 30] [--width 1920] [--height 1080]
    python recording_to_video.py recording.json output.gif [--fps 15] [--width 800] [--height 600]

Requirements:
    - Python 3.7+
    - pycairo
    - Pillow (PIL)
    - ffmpeg (for video output)
"""

import argparse
import json
import os
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Dict, List, Optional, Tuple

try:
    import cairo
except ImportError:
    print("Error: pycairo is required. Install with: pip install pycairo")
    sys.exit(1)

try:
    from PIL import Image
except ImportError:
    print("Error: Pillow is required. Install with: pip install Pillow")
    sys.exit(1)


def parse_color(color_str: str) -> Tuple[float, float, float, float]:
    """Parse a color string (hex ARGB) to RGBA tuple (0-1 range)."""
    if color_str.startswith("#"):
        color_str = color_str[1:]
    
    color_int = int(color_str, 16)
    
    # Extract ARGB components
    a = ((color_int >> 24) & 0xFF) / 255.0
    r = ((color_int >> 16) & 0xFF) / 255.0
    g = ((color_int >> 8) & 0xFF) / 255.0
    b = (color_int & 0xFF) / 255.0
    
    # If alpha is 0, treat as fully opaque (common in xournal++ colors)
    if a == 0:
        a = 1.0
    
    return (r, g, b, a)


def draw_stroke(ctx: cairo.Context, stroke: dict, progress: float = 1.0) -> None:
    """Draw a stroke on the Cairo context."""
    points = stroke.get("points", [])
    if len(points) < 2:
        return
    
    # Calculate how many points to draw based on progress
    num_points = max(2, int(len(points) * progress))
    points = points[:num_points]
    
    color = parse_color(stroke.get("color", "0"))
    width = stroke.get("width", 1.0)
    is_highlighter = stroke.get("is_highlighter", False)
    fill = stroke.get("fill", -1)
    
    ctx.set_line_width(width)
    ctx.set_line_cap(cairo.LINE_CAP_ROUND)
    ctx.set_line_join(cairo.LINE_JOIN_ROUND)
    
    if is_highlighter:
        # Highlighter is semi-transparent
        ctx.set_source_rgba(color[0], color[1], color[2], 0.5)
    else:
        ctx.set_source_rgba(*color)
    
    # Draw the stroke
    ctx.move_to(points[0]["x"], points[0]["y"])
    for point in points[1:]:
        ctx.line_to(point["x"], point["y"])
    
    # Handle variable width strokes
    if any(p.get("z", -1) > 0 for p in points):
        # Variable width stroke - draw with varying line widths
        ctx.stroke()
        for i in range(len(points) - 1):
            p1 = points[i]
            p2 = points[i + 1]
            
            w1 = p1.get("z", width)
            w2 = p2.get("z", width)
            avg_width = (w1 + w2) / 2 if w1 > 0 and w2 > 0 else width
            
            ctx.set_line_width(avg_width)
            ctx.move_to(p1["x"], p1["y"])
            ctx.line_to(p2["x"], p2["y"])
            ctx.stroke()
    else:
        ctx.stroke()
    
    # Handle fill
    if fill >= 0:
        ctx.move_to(points[0]["x"], points[0]["y"])
        for point in points[1:]:
            ctx.line_to(point["x"], point["y"])
        ctx.close_path()
        ctx.set_source_rgba(color[0], color[1], color[2], fill / 255.0)
        ctx.fill()


def draw_image(ctx: cairo.Context, image_info: dict, image_dir: Path) -> None:
    """Draw an image on the Cairo context."""
    filename = image_info.get("filename", "")
    image_path = image_dir / filename
    
    if not image_path.exists():
        return
    
    try:
        img = Image.open(image_path)
        img = img.convert("RGBA")
        
        x = image_info.get("x", 0)
        y = image_info.get("y", 0)
        width = image_info.get("width", img.width)
        height = image_info.get("height", img.height)
        
        # Scale image if needed
        if width != img.width or height != img.height:
            img = img.resize((int(width), int(height)), Image.LANCZOS)
        
        # Convert PIL image to Cairo surface
        arr = bytearray(img.tobytes("raw", "BGRa"))
        surface = cairo.ImageSurface.create_for_data(
            arr, cairo.FORMAT_ARGB32, img.width, img.height
        )
        
        ctx.save()
        ctx.translate(x, y)
        ctx.set_source_surface(surface, 0, 0)
        ctx.paint()
        ctx.restore()
        
    except Exception as e:
        print(f"Warning: Could not load image {filename}: {e}")


def draw_cursor(ctx: cairo.Context, x: float, y: float, cursor_type: str = "pen") -> None:
    """Draw a cursor at the given position."""
    ctx.save()
    ctx.translate(x, y)
    
    if cursor_type == "eraser":
        # Draw eraser cursor (circle)
        ctx.set_source_rgba(0.8, 0.2, 0.2, 0.7)
        ctx.arc(0, 0, 8, 0, 2 * 3.14159)
        ctx.fill()
        ctx.set_source_rgba(1, 1, 1, 0.9)
        ctx.arc(0, 0, 6, 0, 2 * 3.14159)
        ctx.fill()
    else:
        # Draw pen cursor (triangle)
        ctx.set_source_rgba(0.2, 0.2, 0.8, 0.9)
        ctx.move_to(0, 0)
        ctx.line_to(-5, 15)
        ctx.line_to(5, 15)
        ctx.close_path()
        ctx.fill()
    
    ctx.restore()


def generate_frames(recording: dict, image_dir: Path, 
                   width: int, height: int, fps: int) -> Tuple[List[bytes], int, int]:
    """Generate frames from the recording."""
    frames = []
    
    duration_ms = recording.get("duration_ms", 1000)
    total_frames = max(1, int(duration_ms * fps / 1000))
    
    bg_color = parse_color(recording.get("background_color", "ffffff"))
    strokes = recording.get("strokes", [])
    images = recording.get("images", [])
    events = recording.get("events", [])
    
    # Create stroke lookup by ID
    stroke_by_id = {s["id"]: s for s in strokes}
    
    # Track active strokes and their progress
    active_strokes = {}  # stroke_id -> progress (0-1)
    completed_strokes = set()
    visible_images = {}  # image_id -> image_info
    
    current_cursor_pos = None
    current_cursor_type = "pen"
    
    # Process events to build frame state
    event_index = 0
    
    for frame_num in range(total_frames):
        frame_time = int(frame_num * 1000 / fps)
        
        # Process events up to this frame time
        while event_index < len(events) and events[event_index].get("timestamp", 0) <= frame_time:
            event = events[event_index]
            event_type = event.get("type", "")
            
            if event_type == "stroke_start":
                stroke_id = event.get("stroke_id", -1)
                if stroke_id in stroke_by_id:
                    active_strokes[stroke_id] = 0.0
                current_cursor_type = "pen"
                current_cursor_pos = (event.get("x", 0), event.get("y", 0))
                
            elif event_type == "stroke_point":
                stroke_id = event.get("stroke_id", -1)
                if stroke_id in active_strokes:
                    stroke = stroke_by_id.get(stroke_id)
                    if stroke:
                        points = stroke.get("points", [])
                        if points:
                            active_strokes[stroke_id] = min(1.0, active_strokes[stroke_id] + 1.0 / len(points))
                current_cursor_pos = (event.get("x", 0), event.get("y", 0))
                
            elif event_type == "stroke_end":
                stroke_id = event.get("stroke_id", -1)
                if stroke_id in active_strokes:
                    completed_strokes.add(stroke_id)
                    del active_strokes[stroke_id]
                current_cursor_pos = None
                
            elif event_type == "erase_start":
                current_cursor_type = "eraser"
                current_cursor_pos = (event.get("x", 0), event.get("y", 0))
                
            elif event_type == "erase_point":
                current_cursor_pos = (event.get("x", 0), event.get("y", 0))
                # TODO: Handle stroke erasure
                
            elif event_type == "erase_end":
                current_cursor_type = "pen"
                current_cursor_pos = None
                
            elif event_type == "image_add":
                image_id = event.get("image_id", "")
                for img in images:
                    if img.get("id") == image_id:
                        visible_images[image_id] = img.copy()
                        break
                        
            elif event_type == "image_move":
                image_id = event.get("image_id", "")
                if image_id in visible_images:
                    visible_images[image_id]["x"] = event.get("x", 0)
                    visible_images[image_id]["y"] = event.get("y", 0)
                    
            elif event_type == "undo":
                # Simple undo: remove last completed stroke
                if completed_strokes:
                    last_stroke = max(completed_strokes)
                    completed_strokes.remove(last_stroke)
                    
            elif event_type == "redo":
                # Simple redo: not implemented in this basic version
                pass
            
            event_index += 1
        
        # Create frame surface
        surface = cairo.ImageSurface(cairo.FORMAT_ARGB32, width, height)
        ctx = cairo.Context(surface)
        
        # Draw background
        ctx.set_source_rgba(bg_color[0], bg_color[1], bg_color[2], 1.0)
        ctx.paint()
        
        # Draw images
        for img_info in visible_images.values():
            draw_image(ctx, img_info, image_dir)
        
        # Draw completed strokes
        for stroke_id in completed_strokes:
            if stroke_id in stroke_by_id:
                draw_stroke(ctx, stroke_by_id[stroke_id], 1.0)
        
        # Draw active strokes (in progress)
        for stroke_id, progress in active_strokes.items():
            if stroke_id in stroke_by_id:
                draw_stroke(ctx, stroke_by_id[stroke_id], progress)
        
        # Draw cursor
        if current_cursor_pos:
            draw_cursor(ctx, current_cursor_pos[0], current_cursor_pos[1], current_cursor_type)
        
        # Convert surface to bytes
        surface.flush()
        frames.append(surface.get_data().tobytes())
    
    return frames, width, height


def save_as_gif(frames: List[bytes], width: int, height: int, 
                output_path: Path, fps: int) -> None:
    """Save frames as animated GIF."""
    pil_frames = []
    for frame_data in frames:
        # Create PIL image from BGRA data
        img = Image.frombytes("RGBA", (width, height), frame_data, "raw", "BGRa")
        img = img.convert("P", palette=Image.ADAPTIVE, colors=256)
        pil_frames.append(img)
    
    if pil_frames:
        duration = int(1000 / fps)
        pil_frames[0].save(
            output_path,
            save_all=True,
            append_images=pil_frames[1:],
            duration=duration,
            loop=0
        )


def save_as_video(frames: List[bytes], width: int, height: int,
                  output_path: Path, fps: int) -> None:
    """Save frames as video using ffmpeg."""
    # Create temporary directory for PNG frames
    with tempfile.TemporaryDirectory() as temp_dir:
        temp_path = Path(temp_dir)
        
        # Save frames as PNG files
        for i, frame_data in enumerate(frames):
            img = Image.frombytes("RGBA", (width, height), frame_data, "raw", "BGRa")
            img = img.convert("RGB")
            img.save(temp_path / f"frame_{i:06d}.png")
        
        # Use ffmpeg to create video
        cmd = [
            "ffmpeg", "-y",
            "-framerate", str(fps),
            "-i", str(temp_path / "frame_%06d.png"),
            "-c:v", "libx264",
            "-pix_fmt", "yuv420p",
            "-crf", "18",
            str(output_path)
        ]
        
        try:
            subprocess.run(cmd, check=True, capture_output=True)
        except subprocess.CalledProcessError as e:
            print(f"Error: ffmpeg failed: {e.stderr.decode()}")
            sys.exit(1)
        except FileNotFoundError:
            print("Error: ffmpeg not found. Please install ffmpeg.")
            sys.exit(1)


def main():
    parser = argparse.ArgumentParser(
        description="Convert Xournal++ recording to video/GIF"
    )
    parser.add_argument("input", type=Path, help="Input JSON recording file")
    parser.add_argument("output", type=Path, help="Output video/GIF file")
    parser.add_argument("--fps", type=int, default=30, help="Frames per second (default: 30)")
    parser.add_argument("--width", type=int, default=1920, help="Output width (default: 1920)")
    parser.add_argument("--height", type=int, default=1080, help="Output height (default: 1080)")
    parser.add_argument("--image-dir", type=Path, default=None,
                       help="Directory containing images (default: <input>_images)")
    
    args = parser.parse_args()
    
    # Load recording
    if not args.input.exists():
        print(f"Error: Input file not found: {args.input}")
        sys.exit(1)
    
    with open(args.input) as f:
        recording = json.load(f)
    
    # Determine image directory
    if args.image_dir:
        image_dir = args.image_dir
    else:
        image_dir = args.input.parent / (args.input.stem + "_images")
    
    print(f"Generating frames from {args.input}...")
    frames, width, height = generate_frames(
        recording, image_dir, args.width, args.height, args.fps
    )
    
    print(f"Generated {len(frames)} frames")
    
    # Determine output format
    output_ext = args.output.suffix.lower()
    
    if output_ext == ".gif":
        print(f"Saving as GIF: {args.output}")
        save_as_gif(frames, width, height, args.output, args.fps)
    elif output_ext in (".mp4", ".mkv", ".avi", ".mov"):
        print(f"Saving as video: {args.output}")
        save_as_video(frames, width, height, args.output, args.fps)
    else:
        print(f"Error: Unsupported output format: {output_ext}")
        sys.exit(1)
    
    print("Done!")


if __name__ == "__main__":
    main()
