#!/usr/bin/env python3
"""
Xournal++ Recording to Video/GIF Converter

This script reads a recording JSON file generated by Xournal++ and
converts it to a video or GIF using Cairo and ffmpeg.

Usage:
    python recording_to_video.py recording.json output.mp4 [--fps 30] [--width 1920] [--height 1080]
    python recording_to_video.py recording.json output.gif [--fps 15] [--width 800] [--height 600]

Requirements:
    - Python 3.7+
    - pycairo
    - Pillow (PIL)
    - ffmpeg (for video output)
"""

import argparse
import json
import math
import os
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Dict, List, Optional, Tuple

try:
    import cairo
except ImportError:
    print("Error: pycairo is required. Install with: pip install pycairo")
    sys.exit(1)

try:
    from PIL import Image
except ImportError:
    print("Error: Pillow is required. Install with: pip install Pillow")
    sys.exit(1)


def parse_color(color_str: str) -> Tuple[float, float, float, float]:
    """Parse a color string (hex ARGB) to RGBA tuple (0-1 range)."""
    if color_str.startswith("#"):
        color_str = color_str[1:]
    
    # Pad with zeros if needed (for short hex codes)
    color_str = color_str.zfill(8)
    
    try:
        color_int = int(color_str, 16)
    except ValueError:
        # Default to black if parsing fails
        return (0.0, 0.0, 0.0, 1.0)
    
    # Extract ARGB components
    a = ((color_int >> 24) & 0xFF) / 255.0
    r = ((color_int >> 16) & 0xFF) / 255.0
    g = ((color_int >> 8) & 0xFF) / 255.0
    b = (color_int & 0xFF) / 255.0
    
    # If alpha is 0, treat as fully opaque (common in xournal++ colors)
    if a == 0:
        a = 1.0
    
    return (r, g, b, a)


def is_background_dark(color: Tuple[float, float, float, float]) -> bool:
    """Check if background color is dark to adjust contrast."""
    r, g, b, _ = color
    # Calculate luminance (standard formula)
    lum = 0.299 * r + 0.587 * g + 0.114 * b
    return lum < 0.5


def draw_background_pattern(ctx: cairo.Context, width: int, height: int, 
                           bg_color: Tuple[float, float, float, float],
                           pattern_type: str = "plain") -> None:
    """Draw background with optional pattern (dotted, graph, ruled)."""
    is_dark = is_background_dark(bg_color)
    
    # Set pattern color based on background brightness
    if is_dark:
        ctx.set_source_rgba(0.8, 0.8, 0.9, 0.4)  # Light for dark backgrounds
    else:
        ctx.set_source_rgba(0.4, 0.4, 0.5, 0.4)  # Dark for light backgrounds
    
    spacing = 24  # Standard spacing
    
    if pattern_type == "dotted":
        for y in range(0, height, spacing):
            for x in range(0, width, spacing):
                ctx.arc(x, y, 1.0, 0, 2 * math.pi)
                ctx.fill()
                
    elif pattern_type == "graph":
        ctx.set_line_width(0.5)
        for x in range(0, width, spacing):
            ctx.move_to(x, 0)
            ctx.line_to(x, height)
        for y in range(0, height, spacing):
            ctx.move_to(0, y)
            ctx.line_to(width, y)
        ctx.stroke()
        
    elif pattern_type == "ruled":
        ctx.set_line_width(0.5)
        for y in range(spacing, height, spacing):
            ctx.move_to(0, y)
            ctx.line_to(width, y)
        ctx.stroke()


def draw_stroke(ctx: cairo.Context, stroke: dict, progress: float = 1.0) -> None:
    """Draw a stroke on the Cairo context."""
    points = stroke.get("points", [])
    if len(points) < 2:
        return
    
    # Calculate how many points to draw based on progress
    num_points = max(2, int(len(points) * progress))
    points = points[:num_points]
    
    color = parse_color(stroke.get("color", "0"))
    width = stroke.get("width", 1.0)
    is_highlighter = stroke.get("is_highlighter", False)
    fill = stroke.get("fill", -1)
    
    ctx.set_line_width(width)
    ctx.set_line_cap(cairo.LINE_CAP_ROUND)
    ctx.set_line_join(cairo.LINE_JOIN_ROUND)
    
    if is_highlighter:
        # Highlighter is semi-transparent
        ctx.set_source_rgba(color[0], color[1], color[2], 0.5)
    else:
        ctx.set_source_rgba(*color)
    
    # Draw the stroke
    ctx.move_to(points[0]["x"], points[0]["y"])
    for point in points[1:]:
        ctx.line_to(point["x"], point["y"])
    
    # Handle variable width strokes
    if any(p.get("z", -1) > 0 for p in points):
        # Variable width stroke - draw with varying line widths
        ctx.stroke()
        for i in range(len(points) - 1):
            p1 = points[i]
            p2 = points[i + 1]
            
            w1 = p1.get("z", width)
            w2 = p2.get("z", width)
            avg_width = (w1 + w2) / 2 if w1 > 0 and w2 > 0 else width
            
            ctx.set_line_width(avg_width)
            ctx.move_to(p1["x"], p1["y"])
            ctx.line_to(p2["x"], p2["y"])
            ctx.stroke()
    else:
        ctx.stroke()
    
    # Handle fill
    if fill >= 0:
        ctx.move_to(points[0]["x"], points[0]["y"])
        for point in points[1:]:
            ctx.line_to(point["x"], point["y"])
        ctx.close_path()
        ctx.set_source_rgba(color[0], color[1], color[2], fill / 255.0)
        ctx.fill()


def draw_image(ctx: cairo.Context, image_info: dict, image_dir: Path) -> None:
    """Draw an image on the Cairo context."""
    filename = image_info.get("filename", "")
    image_path = image_dir / filename
    
    if not image_path.exists():
        return
    
    try:
        img = Image.open(image_path)
        img = img.convert("RGBA")
        
        x = image_info.get("x", 0)
        y = image_info.get("y", 0)
        width = image_info.get("width", img.width)
        height = image_info.get("height", img.height)
        
        # Scale image if needed
        if width != img.width or height != img.height:
            img = img.resize((int(width), int(height)), Image.LANCZOS)
        
        # Convert PIL image to Cairo surface
        arr = bytearray(img.tobytes("raw", "BGRa"))
        surface = cairo.ImageSurface.create_for_data(
            arr, cairo.FORMAT_ARGB32, img.width, img.height
        )
        
        ctx.save()
        ctx.translate(x, y)
        ctx.set_source_surface(surface, 0, 0)
        ctx.paint()
        ctx.restore()
        
    except Exception as e:
        print(f"Warning: Could not load image {filename}: {e}")


def draw_realistic_pencil(ctx: cairo.Context, x: float, y: float, 
                          tip_color: Tuple[float, float, float, float],
                          scale: float = 1.0, is_dark_bg: bool = False) -> None:
    """Draw a realistic pencil cursor with shadow."""
    ctx.save()
    ctx.translate(x, y)
    
    main_angle_deg = 135
    s = scale * 0.4  # Smaller scale for cursor
    ctx.scale(s, s)
    
    width = 14
    half_w = width / 2
    length = 100
    cone_h = 25
    lead_h = 8
    
    # Draw shadow
    ctx.save()
    ctx.rotate(math.radians(main_angle_deg - 3))
    shadow_len = length * 0.25
    
    grad_shadow = cairo.LinearGradient(0, 0, 0, -shadow_len)
    if is_dark_bg:
        grad_shadow.add_color_stop_rgba(0.0, 0, 0, 0, 0.9)
        grad_shadow.add_color_stop_rgba(1.0, 0, 0, 0, 0.0)
    else:
        grad_shadow.add_color_stop_rgba(0.0, 0, 0, 0, 0.5)
        grad_shadow.add_color_stop_rgba(1.0, 0, 0, 0, 0.0)
    
    ctx.set_source(grad_shadow)
    ctx.move_to(0, 0)
    ctx.line_to(half_w * 0.35, -lead_h)
    ctx.line_to(half_w, -cone_h)
    ctx.line_to(half_w, -shadow_len)
    ctx.line_to(-half_w, -shadow_len)
    ctx.line_to(-half_w, -cone_h)
    ctx.line_to(-half_w * 0.35, -lead_h)
    ctx.close_path()
    ctx.fill()
    ctx.restore()
    
    # Draw pencil body
    ctx.rotate(math.radians(main_angle_deg))
    
    # Lead tip
    blunt_w = 1.5
    ctx.move_to(-blunt_w/2, 0)
    ctx.line_to(blunt_w/2, 0)
    ctx.line_to(half_w * 0.35, -lead_h)
    ctx.line_to(-half_w * 0.35, -lead_h)
    ctx.close_path()
    ctx.set_source_rgb(0.15, 0.15, 0.18)
    ctx.fill()
    
    # Wood cone
    ctx.move_to(-half_w * 0.35, -lead_h)
    ctx.line_to(half_w * 0.35, -lead_h)
    ctx.line_to(half_w, -cone_h)
    ctx.line_to(-half_w, -cone_h)
    ctx.close_path()
    
    pat_wood = cairo.LinearGradient(0, -lead_h, 0, -cone_h)
    pat_wood.add_color_stop_rgb(0.0, 0.85, 0.70, 0.55)
    pat_wood.add_color_stop_rgb(0.3, 0.95, 0.85, 0.70)
    pat_wood.add_color_stop_rgb(1.0, 0.90, 0.80, 0.65)
    ctx.set_source(pat_wood)
    ctx.fill()
    
    # Pencil body (colored part)
    face_w = width / 3.0
    
    # Left face
    ctx.move_to(-half_w, -cone_h)
    ctx.line_to(-half_w + face_w, -cone_h)
    ctx.line_to(-half_w + face_w, -length)
    ctx.line_to(-half_w, -length)
    ctx.close_path()
    ctx.set_source_rgb(tip_color[0] * 0.6, tip_color[1] * 0.6, tip_color[2] * 0.6)
    ctx.fill()
    
    # Center face
    ctx.move_to(-half_w + face_w, -cone_h)
    ctx.line_to(half_w - face_w, -cone_h)
    ctx.line_to(half_w - face_w, -length)
    ctx.line_to(-half_w + face_w, -length)
    ctx.close_path()
    ctx.set_source_rgb(tip_color[0], tip_color[1], tip_color[2])
    ctx.fill()
    
    # Right face
    ctx.move_to(half_w - face_w, -cone_h)
    ctx.line_to(half_w, -cone_h)
    ctx.line_to(half_w, -length)
    ctx.line_to(half_w - face_w, -length)
    ctx.close_path()
    ctx.set_source_rgb(tip_color[0] * 0.8, tip_color[1] * 0.8, tip_color[2] * 0.8)
    ctx.fill()
    
    ctx.restore()


def draw_realistic_eraser(ctx: cairo.Context, x: float, y: float,
                          eraser_size: float = 10, scale: float = 1.0,
                          is_dark_bg: bool = False) -> None:
    """Draw a realistic block eraser cursor with shadow."""
    ctx.save()
    ctx.translate(x, y)
    ctx.rotate(math.radians(-15))
    s = scale * 0.3
    ctx.scale(s, s)
    ctx.translate(-20, -45)
    
    w = 40
    h = 60
    depth = 15
    
    # Draw shadow
    ctx.save()
    ctx.translate(6, 6)
    if is_dark_bg:
        ctx.set_source_rgba(0, 0, 0, 0.7)
    else:
        ctx.set_source_rgba(0, 0, 0, 0.2)
    ctx.move_to(0, h)
    ctx.line_to(w, h)
    ctx.line_to(w + depth, h - 5)
    ctx.line_to(w + depth, -5)
    ctx.line_to(depth, -5)
    ctx.line_to(0, 0)
    ctx.close_path()
    ctx.fill()
    ctx.restore()
    
    # Main body
    ctx.rectangle(0, 0, w, h)
    pat = cairo.LinearGradient(0, 0, w, h)
    pat.add_color_stop_rgb(0, 0.95, 0.95, 0.95)
    pat.add_color_stop_rgb(1, 0.85, 0.85, 0.85)
    ctx.set_source(pat)
    ctx.fill()
    
    # Right side
    ctx.move_to(w, 0)
    ctx.line_to(w + depth, -5)
    ctx.line_to(w + depth, h - 5)
    ctx.line_to(w, h)
    ctx.close_path()
    ctx.set_source_rgb(0.8, 0.8, 0.8)
    ctx.fill()
    
    # Top side
    ctx.move_to(0, 0)
    ctx.line_to(depth, -5)
    ctx.line_to(w + depth, -5)
    ctx.line_to(w, 0)
    ctx.close_path()
    ctx.set_source_rgb(0.9, 0.9, 0.9)
    ctx.fill()
    
    # Blue sleeve
    sleeve_h = h * 0.5
    sleeve_y = h * 0.3
    ctx.rectangle(0, sleeve_y, w, sleeve_h)
    ctx.set_source_rgb(0.2, 0.3, 0.8)
    ctx.fill()
    
    # Sleeve side
    ctx.move_to(w, sleeve_y)
    ctx.line_to(w + depth, sleeve_y - 2)
    ctx.line_to(w + depth, sleeve_y + sleeve_h - 2)
    ctx.line_to(w, sleeve_y + sleeve_h)
    ctx.close_path()
    ctx.set_source_rgb(0.15, 0.25, 0.6)
    ctx.fill()
    
    ctx.restore()


def draw_cursor(ctx: cairo.Context, x: float, y: float, cursor_type: str = "pen",
                eraser_size: float = 10, stroke_color: Tuple[float, float, float, float] = (0, 0, 0, 1),
                is_dark_bg: bool = False) -> None:
    """Draw a cursor at the given position."""
    if cursor_type == "eraser":
        draw_realistic_eraser(ctx, x, y, eraser_size, 1.0, is_dark_bg)
    else:
        draw_realistic_pencil(ctx, x, y, stroke_color, 1.0, is_dark_bg)


def generate_frames(recording: dict, image_dir: Path, 
                   width: int, height: int, fps: int,
                   show_cursor: bool = True,
                   bg_pattern: str = "plain") -> Tuple[List[bytes], int, int]:
    """Generate frames from the recording."""
    frames = []
    
    duration_ms = recording.get("duration_ms", 1000)
    
    # Get page dimensions for scaling
    page_width = recording.get("page_width", 595.0)
    page_height = recording.get("page_height", 842.0)
    
    # Calculate scaling to fit the output dimensions while preserving aspect ratio
    scale_x = width / page_width
    scale_y = height / page_height
    scale = min(scale_x, scale_y)
    
    # Calculate offset to center the page
    offset_x = (width - page_width * scale) / 2
    offset_y = (height - page_height * scale) / 2
    
    bg_color = parse_color(recording.get("background_color", "ffffffff"))
    strokes = recording.get("strokes", [])
    images = recording.get("images", [])
    events = recording.get("events", [])
    
    # Find the first and last event timestamps
    first_event_time = 0
    last_event_time = duration_ms
    if events:
        first_event_time = max(0, events[0].get("timestamp", 0) - 500)
        last_event_time = events[-1].get("timestamp", duration_ms) + 500  # Add 500ms after last event
    
    # Adjust duration to include all events
    adjusted_duration = last_event_time - first_event_time
    total_frames = max(1, int(adjusted_duration * fps / 1000))
    
    # Create stroke lookup by ID
    stroke_by_id = {s["id"]: s for s in strokes}
    
    # Track state
    active_strokes = {}
    completed_strokes = set()
    erased_strokes = set()
    visible_images = {}
    
    # Track eraser path for masking - list of (x, y, size) tuples
    eraser_path: List[Tuple[float, float, float]] = []
    
    current_cursor_pos = None
    current_cursor_type = "pen"
    current_eraser_size = 10
    current_stroke_color = (0.0, 0.0, 0.0, 1.0)
    
    is_dark_bg = is_background_dark(bg_color)
    
    event_index = 0
    
    for frame_num in range(total_frames):
        frame_time = first_event_time + int(frame_num * 1000 / fps)
        
        # Process events up to this frame time
        while event_index < len(events) and events[event_index].get("timestamp", 0) <= frame_time:
            event = events[event_index]
            event_type = event.get("type", "")
            
            if event_type == "stroke_start":
                stroke_id = event.get("stroke_id", -1)
                if stroke_id in stroke_by_id:
                    active_strokes[stroke_id] = 0.0
                    stroke = stroke_by_id[stroke_id]
                    current_stroke_color = parse_color(stroke.get("color", "0"))
                current_cursor_type = "pen"
                current_cursor_pos = (event.get("x", 0), event.get("y", 0))
                
            elif event_type == "stroke_point":
                stroke_id = event.get("stroke_id", -1)
                if stroke_id in active_strokes:
                    stroke = stroke_by_id.get(stroke_id)
                    if stroke:
                        points = stroke.get("points", [])
                        if points:
                            active_strokes[stroke_id] = min(1.0, active_strokes[stroke_id] + 1.0 / len(points))
                current_cursor_pos = (event.get("x", 0), event.get("y", 0))
                
            elif event_type == "stroke_end":
                stroke_id = event.get("stroke_id", -1)
                if stroke_id in active_strokes:
                    completed_strokes.add(stroke_id)
                    del active_strokes[stroke_id]
                current_cursor_pos = None
                
            elif event_type == "erase_start":
                current_cursor_type = "eraser"
                current_eraser_size = event.get("eraser_size", 10)
                current_cursor_pos = (event.get("x", 0), event.get("y", 0))
                # Add starting point of eraser path
                eraser_path.append((event.get("x", 0), event.get("y", 0), current_eraser_size))
                
            elif event_type == "erase_point":
                current_cursor_pos = (event.get("x", 0), event.get("y", 0))
                esize = event.get("eraser_size", current_eraser_size)
                if esize > 0:
                    current_eraser_size = esize
                # Add point to eraser path for masking
                eraser_path.append((event.get("x", 0), event.get("y", 0), current_eraser_size))
                # Also handle affected strokes if provided
                affected = event.get("affected_strokes", [])
                for stroke_id in affected:
                    erased_strokes.add(stroke_id)
                    completed_strokes.discard(stroke_id)
                
            elif event_type == "erase_end":
                current_cursor_type = "pen"
                current_cursor_pos = None
                
            elif event_type == "image_add":
                image_id = event.get("image_id", "")
                for img in images:
                    if img.get("id") == image_id:
                        visible_images[image_id] = img.copy()
                        break
                        
            elif event_type == "image_move":
                image_id = event.get("image_id", "")
                if image_id in visible_images:
                    visible_images[image_id]["x"] = event.get("x", 0)
                    visible_images[image_id]["y"] = event.get("y", 0)
                    
            elif event_type == "undo":
                if completed_strokes:
                    last_stroke = max(completed_strokes)
                    completed_strokes.remove(last_stroke)
                    
            elif event_type == "redo":
                pass
            
            event_index += 1
        
        # Create main frame surface
        surface = cairo.ImageSurface(cairo.FORMAT_ARGB32, width, height)
        ctx = cairo.Context(surface)
        
        # Draw background color
        ctx.set_source_rgba(bg_color[0], bg_color[1], bg_color[2], 1.0)
        ctx.paint()
        
        # Apply transformation for page scaling
        ctx.save()
        ctx.translate(offset_x, offset_y)
        ctx.scale(scale, scale)
        
        # Draw background pattern
        draw_background_pattern(ctx, int(page_width), int(page_height), bg_color, bg_pattern)
        
        ctx.restore()
        
        # Create a separate surface for strokes (so we can erase from it)
        stroke_surface = cairo.ImageSurface(cairo.FORMAT_ARGB32, width, height)
        stroke_ctx = cairo.Context(stroke_surface)
        
        # Apply same transformation to stroke surface
        stroke_ctx.translate(offset_x, offset_y)
        stroke_ctx.scale(scale, scale)
        
        # Draw images on stroke layer
        for img_info in visible_images.values():
            draw_image(stroke_ctx, img_info, image_dir)
        
        # Draw completed strokes (skip fully erased ones)
        for stroke_id in completed_strokes:
            if stroke_id in stroke_by_id and stroke_id not in erased_strokes:
                draw_stroke(stroke_ctx, stroke_by_id[stroke_id], 1.0)
        
        # Draw active strokes (in progress)
        for stroke_id, progress in active_strokes.items():
            if stroke_id in stroke_by_id:
                draw_stroke(stroke_ctx, stroke_by_id[stroke_id], progress)
        
        # Apply eraser mask to stroke surface
        # Use DEST_OUT to cut holes where eraser path is
        if eraser_path:
            stroke_ctx.save()
            stroke_ctx.set_operator(cairo.OPERATOR_DEST_OUT)
            stroke_ctx.set_source_rgba(1, 1, 1, 1)  # Full erase
            stroke_ctx.set_line_cap(cairo.LINE_CAP_ROUND)
            stroke_ctx.set_line_join(cairo.LINE_JOIN_ROUND)
            
            # Draw eraser path as a thick line that removes content
            for i in range(len(eraser_path)):
                ex, ey, esize = eraser_path[i]
                # Draw a filled circle at each point
                stroke_ctx.arc(ex, ey, esize / 2, 0, 2 * math.pi)
                stroke_ctx.fill()
                
                # Also draw lines between consecutive points for smooth erasing
                if i > 0:
                    prev_x, prev_y, prev_size = eraser_path[i - 1]
                    stroke_ctx.set_line_width(max(esize, prev_size))
                    stroke_ctx.move_to(prev_x, prev_y)
                    stroke_ctx.line_to(ex, ey)
                    stroke_ctx.stroke()
            
            stroke_ctx.restore()
        
        # Composite stroke surface onto main surface
        ctx.set_source_surface(stroke_surface, 0, 0)
        ctx.paint()
        
        # Draw cursor on top
        if show_cursor and current_cursor_pos:
            ctx.save()
            ctx.translate(offset_x, offset_y)
            ctx.scale(scale, scale)
            draw_cursor(ctx, current_cursor_pos[0], current_cursor_pos[1],
                       current_cursor_type, current_eraser_size, current_stroke_color, is_dark_bg)
            ctx.restore()
        
        # Convert surface to bytes
        surface.flush()
        frames.append(surface.get_data().tobytes())
    
    return frames, width, height


def save_as_gif(frames: List[bytes], width: int, height: int, 
                output_path: Path, fps: int) -> None:
    """Save frames as animated GIF."""
    pil_frames = []
    for frame_data in frames:
        img = Image.frombytes("RGBA", (width, height), frame_data, "raw", "BGRa")
        img = img.convert("P", palette=Image.ADAPTIVE, colors=256)
        pil_frames.append(img)
    
    if pil_frames:
        duration = int(1000 / fps)
        pil_frames[0].save(
            output_path,
            save_all=True,
            append_images=pil_frames[1:],
            duration=duration,
            loop=0
        )


def save_as_video(frames: List[bytes], width: int, height: int,
                  output_path: Path, fps: int) -> None:
    """Save frames as video using ffmpeg."""
    with tempfile.TemporaryDirectory() as temp_dir:
        temp_path = Path(temp_dir)
        
        for i, frame_data in enumerate(frames):
            img = Image.frombytes("RGBA", (width, height), frame_data, "raw", "BGRa")
            img = img.convert("RGB")
            img.save(temp_path / f"frame_{i:06d}.png")
        
        cmd = [
            "ffmpeg", "-y",
            "-framerate", str(fps),
            "-i", str(temp_path / "frame_%06d.png"),
            "-c:v", "libx264",
            "-pix_fmt", "yuv420p",
            "-crf", "18",
            str(output_path)
        ]
        
        try:
            subprocess.run(cmd, check=True, capture_output=True)
        except subprocess.CalledProcessError as e:
            print(f"Error: ffmpeg failed: {e.stderr.decode()}")
            sys.exit(1)
        except FileNotFoundError:
            print("Error: ffmpeg not found. Please install ffmpeg.")
            sys.exit(1)


def main():
    parser = argparse.ArgumentParser(
        description="Convert Xournal++ recording to video/GIF"
    )
    parser.add_argument("input", type=Path, help="Input JSON recording file")
    parser.add_argument("output", type=Path, help="Output video/GIF file")
    parser.add_argument("--fps", type=int, default=30, help="Frames per second (default: 30)")
    parser.add_argument("--width", type=int, default=1920, help="Output width (default: 1920)")
    parser.add_argument("--height", type=int, default=1080, help="Output height (default: 1080)")
    parser.add_argument("--image-dir", type=Path, default=None,
                       help="Directory containing images (default: <input>_images)")
    parser.add_argument("--no-cursor", action="store_true", help="Hide cursor in video")
    parser.add_argument("--pattern", choices=["plain", "dotted", "graph", "ruled"],
                       default="plain", help="Background pattern (default: plain)")
    
    args = parser.parse_args()
    
    if not args.input.exists():
        print(f"Error: Input file not found: {args.input}")
        sys.exit(1)
    
    with open(args.input) as f:
        recording = json.load(f)
    
    if args.image_dir:
        image_dir = args.image_dir
    else:
        image_dir = args.input.parent / (args.input.stem + "_images")
    
    print(f"Generating frames from {args.input}...")
    frames, width, height = generate_frames(
        recording, image_dir, args.width, args.height, args.fps,
        show_cursor=not args.no_cursor,
        bg_pattern=args.pattern
    )
    
    print(f"Generated {len(frames)} frames")
    
    output_ext = args.output.suffix.lower()
    
    if output_ext == ".gif":
        print(f"Saving as GIF: {args.output}")
        save_as_gif(frames, width, height, args.output, args.fps)
    elif output_ext in (".mp4", ".mkv", ".avi", ".mov"):
        print(f"Saving as video: {args.output}")
        save_as_video(frames, width, height, args.output, args.fps)
    else:
        print(f"Error: Unsupported output format: {output_ext}")
        sys.exit(1)
    
    print("Done!")


if __name__ == "__main__":
    main()
