#!/usr/bin/env python3
"""
Xournal++ Recording to Video/GIF Converter

This script reads a recording JSON file generated by Xournal++ and
converts it to a video or GIF using Cairo and ffmpeg.

Usage:
    python recording_to_video.py recording.json output.mp4 [--fps 30] [--width 1920] [--height 1080]
    python recording_to_video.py recording.json output.gif [--fps 15] [--width 800] [--height 600]
    python recording_to_video.py recording.json output.mp4 --audio  # With sound effects

Requirements:
    - Python 3.7+
    - pycairo
    - Pillow (PIL)
    - ffmpeg (for video output)
    - numpy (optional, for audio)
    - scipy (optional, for audio)
"""

import argparse
import json
import math
import os
import struct
import subprocess
import sys
import tempfile
import wave
from pathlib import Path
from typing import Dict, List, Optional, Tuple

try:
    import cairo
except ImportError:
    print("Error: pycairo is required. Install with: pip install pycairo")
    sys.exit(1)

try:
    from PIL import Image
except ImportError:
    print("Error: Pillow is required. Install with: pip install Pillow")
    sys.exit(1)

# Optional audio support
AUDIO_AVAILABLE = False
try:
    import numpy as np
    AUDIO_AVAILABLE = True
except ImportError:
    pass


# Audio parameters
SAMPLE_RATE = 44100
AUDIO_CHANNELS = 1
AUDIO_SAMPLE_WIDTH = 2  # 16-bit

# Audio file cache
SCRATCH_SOUND = None
TAP_SOUND = None
ERASER_SOUND = None


def load_audio_files(script_dir: Path) -> None:
    """Load audio files from the script directory."""
    global SCRATCH_SOUND, TAP_SOUND, ERASER_SOUND
    
    if not AUDIO_AVAILABLE:
        return
    
    scratch_path = script_dir / "scratch.wav"
    tap_path = script_dir / "tap.wav"
    
    # Load scratch sound (also used for eraser)
    if scratch_path.exists():
        try:
            with wave.open(str(scratch_path), 'rb') as wav_file:
                n_channels = wav_file.getnchannels()
                sample_width = wav_file.getsampwidth()
                framerate = wav_file.getframerate()
                n_frames = wav_file.getnframes()
                audio_data = wav_file.readframes(n_frames)
                
                # Convert to numpy array
                if sample_width == 2:
                    dtype = np.int16
                elif sample_width == 1:
                    dtype = np.uint8
                else:
                    dtype = np.int32
                
                samples = np.frombuffer(audio_data, dtype=dtype).astype(np.float32)
                
                # Convert to mono if stereo
                if n_channels == 2:
                    samples = samples.reshape(-1, 2).mean(axis=1)
                
                # Normalize to -1 to 1
                if dtype == np.int16:
                    samples = samples / 32767.0
                elif dtype == np.uint8:
                    samples = (samples - 128) / 128.0
                
                # Resample if needed
                if framerate != SAMPLE_RATE:
                    old_len = len(samples)
                    new_len = int(old_len * SAMPLE_RATE / framerate)
                    indices = np.linspace(0, old_len - 1, new_len)
                    samples = np.interp(indices, np.arange(old_len), samples)
                
                SCRATCH_SOUND = samples
                ERASER_SOUND = samples  # Use scratch for eraser too
                print(f"Loaded audio: {scratch_path}")
        except Exception as e:
            print(f"Warning: Could not load {scratch_path}: {e}")
    
    # Load tap sound
    if tap_path.exists():
        try:
            with wave.open(str(tap_path), 'rb') as wav_file:
                n_channels = wav_file.getnchannels()
                sample_width = wav_file.getsampwidth()
                framerate = wav_file.getframerate()
                n_frames = wav_file.getnframes()
                audio_data = wav_file.readframes(n_frames)
                
                # Convert to numpy array
                if sample_width == 2:
                    dtype = np.int16
                elif sample_width == 1:
                    dtype = np.uint8
                else:
                    dtype = np.int32
                
                samples = np.frombuffer(audio_data, dtype=dtype).astype(np.float32)
                
                # Convert to mono if stereo
                if n_channels == 2:
                    samples = samples.reshape(-1, 2).mean(axis=1)
                
                # Normalize to -1 to 1
                if dtype == np.int16:
                    samples = samples / 32767.0
                elif dtype == np.uint8:
                    samples = (samples - 128) / 128.0
                
                # Resample if needed
                if framerate != SAMPLE_RATE:
                    old_len = len(samples)
                    new_len = int(old_len * SAMPLE_RATE / framerate)
                    indices = np.linspace(0, old_len - 1, new_len)
                    samples = np.interp(indices, np.arange(old_len), samples)
                
                TAP_SOUND = samples
                print(f"Loaded audio: {tap_path}")
        except Exception as e:
            print(f"Warning: Could not load {tap_path}: {e}")


def get_scratch_chunk(duration_ms: int, speed_factor: float = 1.0, 
                      amplitude: float = 0.3) -> np.ndarray:
    """Get a chunk of scratch sound with specified duration and modulation."""
    if not AUDIO_AVAILABLE:
        return np.array([])
    
    target_samples = int(SAMPLE_RATE * duration_ms / 1000)
    if target_samples == 0:
        return np.array([])
    
    if SCRATCH_SOUND is not None and len(SCRATCH_SOUND) > 0:
        # Use loaded audio file
        source = SCRATCH_SOUND
        source_len = len(source)
        
        # Determine how much of the source to use based on speed
        # Faster speed = higher pitch = compress more source into same time
        pitch_factor = 0.8 + min(speed_factor * 0.4, 1.2)  # 0.8 to 2.0
        source_samples_needed = int(target_samples * pitch_factor)
        
        # Loop the source if needed
        if source_samples_needed > source_len:
            repeats = int(np.ceil(source_samples_needed / source_len))
            source = np.tile(source, repeats)
        
        # Take the required portion and resample to target length
        source_chunk = source[:source_samples_needed]
        indices = np.linspace(0, len(source_chunk) - 1, target_samples)
        sound = np.interp(indices, np.arange(len(source_chunk)), source_chunk)
        
        # Apply amplitude
        sound = sound * amplitude
        
        # Fade in/out
        fade_samples = min(int(SAMPLE_RATE * 0.01), target_samples // 4)
        if fade_samples > 0:
            fade_in = np.linspace(0, 1, fade_samples)
            fade_out = np.linspace(1, 0, fade_samples)
            sound[:fade_samples] *= fade_in
            sound[-fade_samples:] *= fade_out
        
        return (sound * 32767).astype(np.int16)
    else:
        # Fall back to synthetic generation
        return generate_scratch_sound_synthetic(duration_ms, 600 + speed_factor * 400, amplitude)


def get_tap_chunk(amplitude: float = 0.4) -> np.ndarray:
    """Get a tap sound with specified amplitude."""
    if not AUDIO_AVAILABLE:
        return np.array([])
    
    if TAP_SOUND is not None and len(TAP_SOUND) > 0:
        # Use loaded audio file
        sound = TAP_SOUND * amplitude
        return (sound * 32767).astype(np.int16)
    else:
        # Fall back to synthetic generation
        return generate_tap_sound_synthetic(50, 1200, amplitude)


def get_eraser_chunk(duration_ms: int, speed_factor: float = 1.0,
                     amplitude: float = 0.25) -> np.ndarray:
    """Get a chunk of eraser sound with specified duration and modulation."""
    if not AUDIO_AVAILABLE:
        return np.array([])
    
    target_samples = int(SAMPLE_RATE * duration_ms / 1000)
    if target_samples == 0:
        return np.array([])
    
    if ERASER_SOUND is not None and len(ERASER_SOUND) > 0:
        # Use loaded audio file (with lower pitch for eraser)
        source = ERASER_SOUND
        source_len = len(source)
        
        # Lower pitch for eraser (slower playback)
        pitch_factor = 0.5 + min(speed_factor * 0.3, 0.8)  # 0.5 to 1.3
        source_samples_needed = int(target_samples * pitch_factor)
        
        # Loop the source if needed
        if source_samples_needed > source_len:
            repeats = int(np.ceil(source_samples_needed / source_len))
            source = np.tile(source, repeats)
        
        # Take the required portion and resample to target length
        source_chunk = source[:source_samples_needed]
        indices = np.linspace(0, len(source_chunk) - 1, target_samples)
        sound = np.interp(indices, np.arange(len(source_chunk)), source_chunk)
        
        # Apply amplitude
        sound = sound * amplitude
        
        # Fade in/out
        fade_samples = min(int(SAMPLE_RATE * 0.02), target_samples // 4)
        if fade_samples > 0:
            fade_in = np.linspace(0, 1, fade_samples)
            fade_out = np.linspace(1, 0, fade_samples)
            sound[:fade_samples] *= fade_in
            sound[-fade_samples:] *= fade_out
        
        return (sound * 32767).astype(np.int16)
    else:
        # Fall back to synthetic generation
        return generate_eraser_sound_synthetic(duration_ms, amplitude)


def generate_scratch_sound_synthetic(duration_ms: int, frequency: float = 800, 
                                     amplitude: float = 0.3) -> np.ndarray:
    """Generate a synthetic scratch/writing sound effect."""
    if not AUDIO_AVAILABLE:
        return np.array([])
    
    samples = int(SAMPLE_RATE * duration_ms / 1000)
    if samples == 0:
        return np.array([])
    
    t = np.linspace(0, duration_ms / 1000, samples)
    
    # Create a noisy scratch sound by combining multiple frequencies with noise
    noise = np.random.uniform(-1, 1, samples) * 0.3
    
    # Add some tonal component (friction-like)
    tone1 = np.sin(2 * np.pi * frequency * t) * 0.2
    tone2 = np.sin(2 * np.pi * (frequency * 1.5) * t) * 0.1
    
    # Modulate with low frequency to make it sound like friction
    modulation = 0.5 + 0.5 * np.sin(2 * np.pi * 20 * t)
    
    sound = (noise + tone1 + tone2) * modulation * amplitude
    
    # Apply fade in/out
    fade_samples = min(int(SAMPLE_RATE * 0.01), samples // 4)
    if fade_samples > 0:
        fade_in = np.linspace(0, 1, fade_samples)
        fade_out = np.linspace(1, 0, fade_samples)
        sound[:fade_samples] *= fade_in
        sound[-fade_samples:] *= fade_out
    
    return (sound * 32767).astype(np.int16)


def generate_tap_sound_synthetic(duration_ms: int = 50, frequency: float = 1200,
                                 amplitude: float = 0.4) -> np.ndarray:
    """Generate a synthetic short tap sound effect."""
    if not AUDIO_AVAILABLE:
        return np.array([])
    
    samples = int(SAMPLE_RATE * duration_ms / 1000)
    if samples == 0:
        return np.array([])
    
    t = np.linspace(0, duration_ms / 1000, samples)
    
    # Create a short percussive sound
    decay = np.exp(-t * 50)  # Rapid decay
    tone = np.sin(2 * np.pi * frequency * t)
    noise = np.random.uniform(-1, 1, samples) * 0.2
    
    sound = (tone + noise) * decay * amplitude
    
    return (sound * 32767).astype(np.int16)


def generate_eraser_sound_synthetic(duration_ms: int, amplitude: float = 0.25) -> np.ndarray:
    """Generate a synthetic eraser rubbing sound effect."""
    if not AUDIO_AVAILABLE:
        return np.array([])
    
    samples = int(SAMPLE_RATE * duration_ms / 1000)
    if samples == 0:
        return np.array([])
    
    t = np.linspace(0, duration_ms / 1000, samples)
    
    # Eraser sound: lower frequency, more "whooshy"
    noise = np.random.uniform(-1, 1, samples)
    
    # Low-pass filter effect using moving average
    window_size = 50
    if samples > window_size:
        noise = np.convolve(noise, np.ones(window_size) / window_size, mode='same')
    
    # Add some low rumble
    rumble = np.sin(2 * np.pi * 100 * t) * 0.1
    
    # Modulate
    modulation = 0.7 + 0.3 * np.sin(2 * np.pi * 15 * t)
    
    sound = (noise + rumble) * modulation * amplitude
    
    # Fade in/out
    fade_samples = min(int(SAMPLE_RATE * 0.02), samples // 4)
    if fade_samples > 0:
        fade_in = np.linspace(0, 1, fade_samples)
        fade_out = np.linspace(1, 0, fade_samples)
        sound[:fade_samples] *= fade_in
        sound[-fade_samples:] *= fade_out
    
    return (sound * 32767).astype(np.int16)


def create_audio_track(events: List[dict], duration_ms: int, 
                       first_event_time: int) -> Optional[bytes]:
    """Create an audio track synchronized with the recording events."""
    if not AUDIO_AVAILABLE:
        print("Warning: numpy not available, audio disabled")
        return None
    
    # Create a silent audio track
    total_samples = int(SAMPLE_RATE * (duration_ms + 1000) / 1000)
    audio_track = np.zeros(total_samples, dtype=np.float32)
    
    # Track stroke and eraser segments for sound generation
    current_stroke_start = None
    current_stroke_points = []
    current_eraser_start = None
    current_eraser_points = []
    
    for event in events:
        event_type = event.get("type", "")
        timestamp = event.get("timestamp", 0) - first_event_time
        
        if event_type == "stroke_start":
            current_stroke_start = timestamp
            current_stroke_points = [(event.get("x", 0), event.get("y", 0), timestamp)]
            
        elif event_type == "stroke_point":
            if current_stroke_start is not None:
                current_stroke_points.append((event.get("x", 0), event.get("y", 0), timestamp))
                
        elif event_type == "stroke_end":
            if current_stroke_start is not None and len(current_stroke_points) >= 2:
                # Calculate stroke characteristics
                stroke_duration = timestamp - current_stroke_start
                
                # Calculate total distance and average speed
                total_distance = 0
                for i in range(1, len(current_stroke_points)):
                    p1 = current_stroke_points[i - 1]
                    p2 = current_stroke_points[i]
                    total_distance += math.hypot(p2[0] - p1[0], p2[1] - p1[1])
                
                avg_speed = total_distance / max(stroke_duration, 1) * 1000  # pixels per second
                
                if stroke_duration < 100 or total_distance < 20:
                    # Short stroke = tap sound
                    sound = get_tap_chunk(min(0.5, 0.2 + avg_speed / 2000))
                    start_sample = int(current_stroke_start * SAMPLE_RATE / 1000)
                    end_sample = min(start_sample + len(sound), total_samples)
                    if start_sample < total_samples and len(sound) > 0:
                        audio_track[start_sample:end_sample] += sound[:end_sample - start_sample].astype(np.float32) / 32767
                else:
                    # Longer stroke = scratch sound, modulated by speed
                    # Generate sound in chunks based on point segments
                    for i in range(1, len(current_stroke_points)):
                        p1 = current_stroke_points[i - 1]
                        p2 = current_stroke_points[i]
                        
                        segment_dist = math.hypot(p2[0] - p1[0], p2[1] - p1[1])
                        segment_time = p2[2] - p1[2]
                        
                        if segment_time > 0 and segment_dist > 1:
                            segment_speed = segment_dist / segment_time * 1000
                            # Amplitude based on speed
                            amp = min(0.4, 0.1 + segment_speed / 3000)
                            # Speed factor for pitch modulation
                            speed_factor = segment_speed / 500  # normalize
                            
                            sound = get_scratch_chunk(int(segment_time), speed_factor, amp)
                            start_sample = int(p1[2] * SAMPLE_RATE / 1000)
                            end_sample = min(start_sample + len(sound), total_samples)
                            if start_sample < total_samples and len(sound) > 0:
                                audio_track[start_sample:end_sample] += sound[:end_sample - start_sample].astype(np.float32) / 32767
            
            current_stroke_start = None
            current_stroke_points = []
            
        elif event_type == "erase_start":
            current_eraser_start = timestamp
            current_eraser_points = [(event.get("x", 0), event.get("y", 0), timestamp)]
            
        elif event_type == "erase_point":
            if current_eraser_start is not None:
                current_eraser_points.append((event.get("x", 0), event.get("y", 0), timestamp))
                
        elif event_type == "erase_end":
            if current_eraser_start is not None and len(current_eraser_points) >= 2:
                # Generate eraser sound based on movement
                for i in range(1, len(current_eraser_points)):
                    p1 = current_eraser_points[i - 1]
                    p2 = current_eraser_points[i]
                    
                    segment_dist = math.hypot(p2[0] - p1[0], p2[1] - p1[1])
                    segment_time = p2[2] - p1[2]
                    
                    if segment_time > 0 and segment_dist > 1:
                        segment_speed = segment_dist / segment_time * 1000
                        amp = min(0.35, 0.1 + segment_speed / 3000)
                        speed_factor = segment_speed / 500  # normalize
                        
                        sound = get_eraser_chunk(int(segment_time), speed_factor, amp)
                        start_sample = int(p1[2] * SAMPLE_RATE / 1000)
                        end_sample = min(start_sample + len(sound), total_samples)
                        if start_sample < total_samples and len(sound) > 0:
                            audio_track[start_sample:end_sample] += sound[:end_sample - start_sample].astype(np.float32) / 32767
            
            current_eraser_start = None
            current_eraser_points = []
    
    # Normalize and clip
    max_val = np.max(np.abs(audio_track))
    if max_val > 0:
        audio_track = audio_track / max_val * 0.8
    audio_track = np.clip(audio_track, -1.0, 1.0)
    
    # Convert to 16-bit PCM
    audio_data = (audio_track * 32767).astype(np.int16)
    
    return audio_data.tobytes()


def save_audio_wav(audio_data: bytes, filepath: Path) -> None:
    """Save audio data to a WAV file."""
    with wave.open(str(filepath), 'w') as wav_file:
        wav_file.setnchannels(AUDIO_CHANNELS)
        wav_file.setsampwidth(AUDIO_SAMPLE_WIDTH)
        wav_file.setframerate(SAMPLE_RATE)
        wav_file.writeframes(audio_data)


def parse_color(color_str: str) -> Tuple[float, float, float, float]:
    """Parse a color string (hex ARGB) to RGBA tuple (0-1 range)."""
    if color_str.startswith("#"):
        color_str = color_str[1:]
    
    # Pad with zeros if needed (for short hex codes)
    color_str = color_str.zfill(8)
    
    try:
        color_int = int(color_str, 16)
    except ValueError:
        # Default to black if parsing fails
        return (0.0, 0.0, 0.0, 1.0)
    
    # Extract ARGB components
    a = ((color_int >> 24) & 0xFF) / 255.0
    r = ((color_int >> 16) & 0xFF) / 255.0
    g = ((color_int >> 8) & 0xFF) / 255.0
    b = (color_int & 0xFF) / 255.0
    
    # If alpha is 0, treat as fully opaque (common in xournal++ colors)
    if a == 0:
        a = 1.0
    
    return (r, g, b, a)


def is_background_dark(color: Tuple[float, float, float, float]) -> bool:
    """Check if background color is dark to adjust contrast."""
    r, g, b, _ = color
    # Calculate luminance (standard formula)
    lum = 0.299 * r + 0.587 * g + 0.114 * b
    return lum < 0.5


def draw_background_pattern(ctx: cairo.Context, width: int, height: int, 
                           bg_color: Tuple[float, float, float, float],
                           pattern_type: str = "plain") -> None:
    """Draw background with optional pattern (dotted, graph, ruled)."""
    is_dark = is_background_dark(bg_color)
    
    # Set pattern color based on background brightness
    if is_dark:
        ctx.set_source_rgba(0.8, 0.8, 0.9, 0.4)  # Light for dark backgrounds
    else:
        ctx.set_source_rgba(0.4, 0.4, 0.5, 0.4)  # Dark for light backgrounds
    
    spacing = 24  # Standard spacing
    
    if pattern_type == "dotted":
        for y in range(0, height, spacing):
            for x in range(0, width, spacing):
                ctx.arc(x, y, 1.0, 0, 2 * math.pi)
                ctx.fill()
                
    elif pattern_type == "graph":
        ctx.set_line_width(0.5)
        for x in range(0, width, spacing):
            ctx.move_to(x, 0)
            ctx.line_to(x, height)
        for y in range(0, height, spacing):
            ctx.move_to(0, y)
            ctx.line_to(width, y)
        ctx.stroke()
        
    elif pattern_type == "ruled":
        ctx.set_line_width(0.5)
        for y in range(spacing, height, spacing):
            ctx.move_to(0, y)
            ctx.line_to(width, y)
        ctx.stroke()


def draw_stroke(ctx: cairo.Context, stroke: dict, progress: float = 1.0) -> None:
    """Draw a stroke on the Cairo context."""
    points = stroke.get("points", [])
    if len(points) < 2:
        return
    
    # Calculate how many points to draw based on progress
    num_points = max(2, int(len(points) * progress))
    points = points[:num_points]
    
    color = parse_color(stroke.get("color", "0"))
    base_width = stroke.get("width", 1.0)
    is_highlighter = stroke.get("is_highlighter", False)
    fill = stroke.get("fill", -1)
    
    ctx.set_line_cap(cairo.LINE_CAP_ROUND)
    ctx.set_line_join(cairo.LINE_JOIN_ROUND)
    
    if is_highlighter:
        # Highlighter is semi-transparent
        ctx.set_source_rgba(color[0], color[1], color[2], 0.5)
    else:
        ctx.set_source_rgba(*color)
    
    # Check if stroke has variable width (pressure data in 'z' field)
    # In Xournal++, z=-1 means no pressure data, z>0 is pressure
    has_pressure = any(p.get("z", -1) > 0 for p in points)
    
    if has_pressure:
        # Variable width stroke - draw segment by segment with varying line widths
        for i in range(len(points) - 1):
            p1 = points[i]
            p2 = points[i + 1]
            
            # z is pressure, use it to scale width
            # Pressure typically ranges from 0 to 1, but can vary
            z1 = p1.get("z", -1)
            z2 = p2.get("z", -1)
            
            if z1 > 0 and z2 > 0:
                # Pressure is stored, scale width by pressure
                # Average pressure for segment
                avg_pressure = (z1 + z2) / 2
                # Scale width: pressure is usually 0-1 range, multiply base_width
                segment_width = max(0.5, base_width * avg_pressure)
            else:
                segment_width = base_width
            
            ctx.set_line_width(segment_width)
            ctx.move_to(p1["x"], p1["y"])
            ctx.line_to(p2["x"], p2["y"])
            ctx.stroke()
    else:
        # Fixed width stroke - draw as single path
        ctx.set_line_width(base_width)
        ctx.move_to(points[0]["x"], points[0]["y"])
        for point in points[1:]:
            ctx.line_to(point["x"], point["y"])
        ctx.stroke()
    
    # Handle fill
    if fill >= 0:
        ctx.move_to(points[0]["x"], points[0]["y"])
        for point in points[1:]:
            ctx.line_to(point["x"], point["y"])
        ctx.close_path()
        ctx.set_source_rgba(color[0], color[1], color[2], fill / 255.0)
        ctx.fill()


def draw_image(ctx: cairo.Context, image_info: dict, image_dir: Path) -> None:
    """Draw an image on the Cairo context with support for transformations."""
    filename = image_info.get("filename", "")
    image_path = image_dir / filename
    
    if not image_path.exists():
        return
    
    try:
        img = Image.open(image_path)
        img = img.convert("RGBA")
        
        x = image_info.get("x", 0)
        y = image_info.get("y", 0)
        width = image_info.get("width", img.width)
        height = image_info.get("height", img.height)
        rotation = image_info.get("rotation", 0)  # Rotation in radians
        
        # Scale image if needed
        target_width = int(width)
        target_height = int(height)
        if target_width != img.width or target_height != img.height:
            img = img.resize((target_width, target_height), Image.LANCZOS)
        
        # Convert PIL image to Cairo surface
        arr = bytearray(img.tobytes("raw", "BGRa"))
        surface = cairo.ImageSurface.create_for_data(
            arr, cairo.FORMAT_ARGB32, img.width, img.height
        )
        
        ctx.save()
        
        # Apply transformations
        if rotation != 0:
            # Translate to center of image, rotate, then translate back
            center_x = x + width / 2
            center_y = y + height / 2
            ctx.translate(center_x, center_y)
            ctx.rotate(rotation)
            ctx.translate(-width / 2, -height / 2)
        else:
            ctx.translate(x, y)
        
        ctx.set_source_surface(surface, 0, 0)
        ctx.paint()
        ctx.restore()
        
    except Exception as e:
        print(f"Warning: Could not load image {filename}: {e}")


def draw_realistic_pencil(ctx: cairo.Context, x: float, y: float, 
                          tip_color: Tuple[float, float, float, float],
                          scale: float = 1.0, is_dark_bg: bool = False) -> None:
    """Draw a realistic pencil cursor with shadow."""
    ctx.save()
    ctx.translate(x, y)
    
    main_angle_deg = 135
    s = scale * 0.4  # Smaller scale for cursor
    ctx.scale(s, s)
    
    width = 14
    half_w = width / 2
    length = 100
    cone_h = 25
    lead_h = 8
    
    # Draw shadow
    ctx.save()
    ctx.rotate(math.radians(main_angle_deg - 3))
    shadow_len = length * 0.25
    
    grad_shadow = cairo.LinearGradient(0, 0, 0, -shadow_len)
    if is_dark_bg:
        grad_shadow.add_color_stop_rgba(0.0, 0, 0, 0, 0.9)
        grad_shadow.add_color_stop_rgba(1.0, 0, 0, 0, 0.0)
    else:
        grad_shadow.add_color_stop_rgba(0.0, 0, 0, 0, 0.5)
        grad_shadow.add_color_stop_rgba(1.0, 0, 0, 0, 0.0)
    
    ctx.set_source(grad_shadow)
    ctx.move_to(0, 0)
    ctx.line_to(half_w * 0.35, -lead_h)
    ctx.line_to(half_w, -cone_h)
    ctx.line_to(half_w, -shadow_len)
    ctx.line_to(-half_w, -shadow_len)
    ctx.line_to(-half_w, -cone_h)
    ctx.line_to(-half_w * 0.35, -lead_h)
    ctx.close_path()
    ctx.fill()
    ctx.restore()
    
    # Draw pencil body
    ctx.rotate(math.radians(main_angle_deg))
    
    # Lead tip
    blunt_w = 1.5
    ctx.move_to(-blunt_w/2, 0)
    ctx.line_to(blunt_w/2, 0)
    ctx.line_to(half_w * 0.35, -lead_h)
    ctx.line_to(-half_w * 0.35, -lead_h)
    ctx.close_path()
    ctx.set_source_rgb(0.15, 0.15, 0.18)
    ctx.fill()
    
    # Wood cone
    ctx.move_to(-half_w * 0.35, -lead_h)
    ctx.line_to(half_w * 0.35, -lead_h)
    ctx.line_to(half_w, -cone_h)
    ctx.line_to(-half_w, -cone_h)
    ctx.close_path()
    
    pat_wood = cairo.LinearGradient(0, -lead_h, 0, -cone_h)
    pat_wood.add_color_stop_rgb(0.0, 0.85, 0.70, 0.55)
    pat_wood.add_color_stop_rgb(0.3, 0.95, 0.85, 0.70)
    pat_wood.add_color_stop_rgb(1.0, 0.90, 0.80, 0.65)
    ctx.set_source(pat_wood)
    ctx.fill()
    
    # Pencil body (colored part)
    face_w = width / 3.0
    
    # Left face
    ctx.move_to(-half_w, -cone_h)
    ctx.line_to(-half_w + face_w, -cone_h)
    ctx.line_to(-half_w + face_w, -length)
    ctx.line_to(-half_w, -length)
    ctx.close_path()
    ctx.set_source_rgb(tip_color[0] * 0.6, tip_color[1] * 0.6, tip_color[2] * 0.6)
    ctx.fill()
    
    # Center face
    ctx.move_to(-half_w + face_w, -cone_h)
    ctx.line_to(half_w - face_w, -cone_h)
    ctx.line_to(half_w - face_w, -length)
    ctx.line_to(-half_w + face_w, -length)
    ctx.close_path()
    ctx.set_source_rgb(tip_color[0], tip_color[1], tip_color[2])
    ctx.fill()
    
    # Right face
    ctx.move_to(half_w - face_w, -cone_h)
    ctx.line_to(half_w, -cone_h)
    ctx.line_to(half_w, -length)
    ctx.line_to(half_w - face_w, -length)
    ctx.close_path()
    ctx.set_source_rgb(tip_color[0] * 0.8, tip_color[1] * 0.8, tip_color[2] * 0.8)
    ctx.fill()
    
    ctx.restore()


def draw_realistic_eraser(ctx: cairo.Context, x: float, y: float,
                          eraser_size: float = 10, scale: float = 1.0,
                          is_dark_bg: bool = False) -> None:
    """Draw a realistic block eraser cursor with shadow."""
    ctx.save()
    ctx.translate(x, y)
    ctx.rotate(math.radians(-15))
    s = scale * 0.3
    ctx.scale(s, s)
    ctx.translate(-20, -45)
    
    w = 40
    h = 60
    depth = 15
    
    # Draw shadow
    ctx.save()
    ctx.translate(6, 6)
    if is_dark_bg:
        ctx.set_source_rgba(0, 0, 0, 0.7)
    else:
        ctx.set_source_rgba(0, 0, 0, 0.2)
    ctx.move_to(0, h)
    ctx.line_to(w, h)
    ctx.line_to(w + depth, h - 5)
    ctx.line_to(w + depth, -5)
    ctx.line_to(depth, -5)
    ctx.line_to(0, 0)
    ctx.close_path()
    ctx.fill()
    ctx.restore()
    
    # Main body
    ctx.rectangle(0, 0, w, h)
    pat = cairo.LinearGradient(0, 0, w, h)
    pat.add_color_stop_rgb(0, 0.95, 0.95, 0.95)
    pat.add_color_stop_rgb(1, 0.85, 0.85, 0.85)
    ctx.set_source(pat)
    ctx.fill()
    
    # Right side
    ctx.move_to(w, 0)
    ctx.line_to(w + depth, -5)
    ctx.line_to(w + depth, h - 5)
    ctx.line_to(w, h)
    ctx.close_path()
    ctx.set_source_rgb(0.8, 0.8, 0.8)
    ctx.fill()
    
    # Top side
    ctx.move_to(0, 0)
    ctx.line_to(depth, -5)
    ctx.line_to(w + depth, -5)
    ctx.line_to(w, 0)
    ctx.close_path()
    ctx.set_source_rgb(0.9, 0.9, 0.9)
    ctx.fill()
    
    # Blue sleeve
    sleeve_h = h * 0.5
    sleeve_y = h * 0.3
    ctx.rectangle(0, sleeve_y, w, sleeve_h)
    ctx.set_source_rgb(0.2, 0.3, 0.8)
    ctx.fill()
    
    # Sleeve side
    ctx.move_to(w, sleeve_y)
    ctx.line_to(w + depth, sleeve_y - 2)
    ctx.line_to(w + depth, sleeve_y + sleeve_h - 2)
    ctx.line_to(w, sleeve_y + sleeve_h)
    ctx.close_path()
    ctx.set_source_rgb(0.15, 0.25, 0.6)
    ctx.fill()
    
    ctx.restore()


def draw_cursor(ctx: cairo.Context, x: float, y: float, cursor_type: str = "pen",
                eraser_size: float = 10, stroke_color: Tuple[float, float, float, float] = (0, 0, 0, 1),
                is_dark_bg: bool = False) -> None:
    """Draw a cursor at the given position."""
    if cursor_type == "eraser":
        draw_realistic_eraser(ctx, x, y, eraser_size, 1.0, is_dark_bg)
    else:
        draw_realistic_pencil(ctx, x, y, stroke_color, 1.0, is_dark_bg)


def generate_frames(recording: dict, image_dir: Path, 
                   width: Optional[int], height: Optional[int], fps: int,
                   show_cursor: bool = True,
                   bg_pattern: str = "plain",
                   scale_factor: float = 1.0) -> Tuple[List[bytes], int, int, int]:
    """Generate frames from the recording. Returns (frames, width, height, first_event_time)."""
    frames = []
    
    duration_ms = recording.get("duration_ms", 1000)
    
    # Get page dimensions from recording
    page_width = recording.get("page_width", 595.0)  # Default A4 width in points
    page_height = recording.get("page_height", 842.0)  # Default A4 height in points
    
    # If width/height not specified, use page dimensions directly (scaled)
    if width is None or height is None:
        # Use page size with scale factor (default 2x for HD quality)
        width = int(page_width * scale_factor)
        height = int(page_height * scale_factor)
    
    # Ensure even dimensions (required by h264 with yuv420p)
    width = (width + 1) // 2 * 2
    height = (height + 1) // 2 * 2
    
    # Calculate scaling to fit the output dimensions while preserving aspect ratio
    scale_x = width / page_width
    scale_y = height / page_height
    scale = min(scale_x, scale_y)
    
    # Calculate offset to center the page
    offset_x = (width - page_width * scale) / 2
    offset_y = (height - page_height * scale) / 2
    
    bg_color = parse_color(recording.get("background_color", "ffffffff"))
    strokes = recording.get("strokes", [])
    images = recording.get("images", [])
    events = recording.get("events", [])
    
    # Find the first and last event timestamps
    first_event_time = 0
    last_event_time = duration_ms
    if events:
        first_event_time = max(0, events[0].get("timestamp", 0) - 500)
        last_event_time = events[-1].get("timestamp", duration_ms) + 500  # Add 500ms after last event
    
    # Adjust duration to include all events
    adjusted_duration = last_event_time - first_event_time
    total_frames = max(1, int(adjusted_duration * fps / 1000))
    
    # Create stroke lookup by ID
    stroke_by_id = {s["id"]: s for s in strokes}
    
    # Track state
    active_strokes = {}
    completed_strokes = set()
    erased_strokes = set()
    visible_images = {}
    
    # Track eraser path for masking - list of (x, y, size) tuples
    eraser_path: List[Tuple[float, float, float]] = []
    
    current_cursor_pos = None
    current_cursor_type = "pen"
    current_eraser_size = 10
    current_stroke_color = (0.0, 0.0, 0.0, 1.0)
    
    is_dark_bg = is_background_dark(bg_color)
    
    event_index = 0
    
    for frame_num in range(total_frames):
        frame_time = first_event_time + int(frame_num * 1000 / fps)
        
        # Process events up to this frame time
        while event_index < len(events) and events[event_index].get("timestamp", 0) <= frame_time:
            event = events[event_index]
            event_type = event.get("type", "")
            
            if event_type == "stroke_start":
                stroke_id = event.get("stroke_id", -1)
                if stroke_id in stroke_by_id:
                    active_strokes[stroke_id] = 0.0
                    stroke = stroke_by_id[stroke_id]
                    current_stroke_color = parse_color(stroke.get("color", "0"))
                current_cursor_type = "pen"
                current_cursor_pos = (event.get("x", 0), event.get("y", 0))
                
            elif event_type == "stroke_point":
                stroke_id = event.get("stroke_id", -1)
                if stroke_id in active_strokes:
                    stroke = stroke_by_id.get(stroke_id)
                    if stroke:
                        points = stroke.get("points", [])
                        if points:
                            active_strokes[stroke_id] = min(1.0, active_strokes[stroke_id] + 1.0 / len(points))
                current_cursor_pos = (event.get("x", 0), event.get("y", 0))
                
            elif event_type == "stroke_end":
                stroke_id = event.get("stroke_id", -1)
                if stroke_id in active_strokes:
                    completed_strokes.add(stroke_id)
                    del active_strokes[stroke_id]
                current_cursor_pos = None
                
            elif event_type == "erase_start":
                current_cursor_type = "eraser"
                current_eraser_size = event.get("eraser_size", 10)
                current_cursor_pos = (event.get("x", 0), event.get("y", 0))
                # Add starting point of eraser path
                eraser_path.append((event.get("x", 0), event.get("y", 0), current_eraser_size))
                
            elif event_type == "erase_point":
                current_cursor_pos = (event.get("x", 0), event.get("y", 0))
                esize = event.get("eraser_size", current_eraser_size)
                if esize > 0:
                    current_eraser_size = esize
                # Add point to eraser path for masking
                eraser_path.append((event.get("x", 0), event.get("y", 0), current_eraser_size))
                # Also handle affected strokes if provided
                affected = event.get("affected_strokes", [])
                for stroke_id in affected:
                    erased_strokes.add(stroke_id)
                    completed_strokes.discard(stroke_id)
                
            elif event_type == "erase_end":
                current_cursor_type = "pen"
                current_cursor_pos = None
                
            elif event_type == "image_add":
                image_id = event.get("image_id", "")
                for img in images:
                    if img.get("id") == image_id:
                        visible_images[image_id] = img.copy()
                        visible_images[image_id]["z_order"] = event.get("z_order", 0)
                        break
            
            elif event_type == "image_copy":
                image_id = event.get("image_id", "")
                for img in images:
                    if img.get("id") == image_id:
                        visible_images[image_id] = img.copy()
                        visible_images[image_id]["x"] = event.get("x", 0)
                        visible_images[image_id]["y"] = event.get("y", 0)
                        visible_images[image_id]["width"] = event.get("width", img.get("width", 100))
                        visible_images[image_id]["height"] = event.get("height", img.get("height", 100))
                        visible_images[image_id]["z_order"] = event.get("z_order", 0)
                        break
                        
            elif event_type == "image_move":
                image_id = event.get("image_id", "")
                if image_id in visible_images:
                    visible_images[image_id]["x"] = event.get("x", 0)
                    visible_images[image_id]["y"] = event.get("y", 0)
            
            elif event_type == "image_resize":
                image_id = event.get("image_id", "")
                if image_id in visible_images:
                    visible_images[image_id]["x"] = event.get("x", 0)
                    visible_images[image_id]["y"] = event.get("y", 0)
                    visible_images[image_id]["width"] = event.get("width", visible_images[image_id].get("width", 100))
                    visible_images[image_id]["height"] = event.get("height", visible_images[image_id].get("height", 100))
            
            elif event_type == "image_rotate":
                image_id = event.get("image_id", "")
                if image_id in visible_images:
                    visible_images[image_id]["rotation"] = event.get("rotation", 0)
            
            elif event_type == "element_z_change":
                element_id = event.get("element_id", "")
                new_z = event.get("z_order", 0)
                if element_id in visible_images:
                    visible_images[element_id]["z_order"] = new_z
                    
            elif event_type == "undo":
                if completed_strokes:
                    last_stroke = max(completed_strokes)
                    completed_strokes.remove(last_stroke)
                    
            elif event_type == "redo":
                pass
            
            event_index += 1
        
        # Create main frame surface
        surface = cairo.ImageSurface(cairo.FORMAT_ARGB32, width, height)
        ctx = cairo.Context(surface)
        
        # Draw background color
        ctx.set_source_rgba(bg_color[0], bg_color[1], bg_color[2], 1.0)
        ctx.paint()
        
        # Apply transformation for page scaling
        ctx.save()
        ctx.translate(offset_x, offset_y)
        ctx.scale(scale, scale)
        
        # Draw background pattern
        draw_background_pattern(ctx, int(page_width), int(page_height), bg_color, bg_pattern)
        
        ctx.restore()
        
        # Create a separate surface for strokes (so we can erase from it)
        stroke_surface = cairo.ImageSurface(cairo.FORMAT_ARGB32, width, height)
        stroke_ctx = cairo.Context(stroke_surface)
        
        # Apply same transformation to stroke surface
        stroke_ctx.translate(offset_x, offset_y)
        stroke_ctx.scale(scale, scale)
        
        # Collect all elements (images and strokes) with their z-order
        # so we can render them in the correct order
        elements_to_draw = []
        
        # Add images to draw list
        for img_id, img_info in visible_images.items():
            z = img_info.get("z_order", 0)
            elements_to_draw.append(("image", z, img_info))
        
        # Add completed strokes to draw list
        for stroke_id in completed_strokes:
            if stroke_id in stroke_by_id and stroke_id not in erased_strokes:
                stroke = stroke_by_id[stroke_id]
                z = stroke.get("z_order", 0)
                elements_to_draw.append(("stroke", z, stroke, 1.0))
        
        # Add active strokes to draw list
        for stroke_id, progress in active_strokes.items():
            if stroke_id in stroke_by_id:
                stroke = stroke_by_id[stroke_id]
                z = stroke.get("z_order", 0)
                elements_to_draw.append(("stroke", z, stroke, progress))
        
        # Sort by z-order (lower z-order draws first, appears behind)
        elements_to_draw.sort(key=lambda x: x[1])
        
        # Draw all elements in z-order
        for elem in elements_to_draw:
            if elem[0] == "image":
                draw_image(stroke_ctx, elem[2], image_dir)
            elif elem[0] == "stroke":
                draw_stroke(stroke_ctx, elem[2], elem[3])
        
        # Apply eraser mask to stroke surface
        # Use DEST_OUT to cut holes where eraser path is
        if eraser_path:
            stroke_ctx.save()
            stroke_ctx.set_operator(cairo.OPERATOR_DEST_OUT)
            stroke_ctx.set_source_rgba(1, 1, 1, 1)  # Full erase
            stroke_ctx.set_line_cap(cairo.LINE_CAP_ROUND)
            stroke_ctx.set_line_join(cairo.LINE_JOIN_ROUND)
            
            # Draw eraser path as a thick line that removes content
            for i in range(len(eraser_path)):
                ex, ey, esize = eraser_path[i]
                # Draw a filled circle at each point
                stroke_ctx.arc(ex, ey, esize / 2, 0, 2 * math.pi)
                stroke_ctx.fill()
                
                # Also draw lines between consecutive points for smooth erasing
                if i > 0:
                    prev_x, prev_y, prev_size = eraser_path[i - 1]
                    stroke_ctx.set_line_width(max(esize, prev_size))
                    stroke_ctx.move_to(prev_x, prev_y)
                    stroke_ctx.line_to(ex, ey)
                    stroke_ctx.stroke()
            
            stroke_ctx.restore()
        
        # Composite stroke surface onto main surface
        ctx.set_source_surface(stroke_surface, 0, 0)
        ctx.paint()
        
        # Draw cursor on top
        if show_cursor and current_cursor_pos:
            ctx.save()
            ctx.translate(offset_x, offset_y)
            ctx.scale(scale, scale)
            draw_cursor(ctx, current_cursor_pos[0], current_cursor_pos[1],
                       current_cursor_type, current_eraser_size, current_stroke_color, is_dark_bg)
            ctx.restore()
        
        # Convert surface to bytes
        surface.flush()
        frames.append(surface.get_data().tobytes())
    
    return frames, width, height, first_event_time


def save_as_gif(frames: List[bytes], width: int, height: int, 
                output_path: Path, fps: int) -> None:
    """Save frames as animated GIF."""
    pil_frames = []
    for frame_data in frames:
        img = Image.frombytes("RGBA", (width, height), frame_data, "raw", "BGRa")
        img = img.convert("P", palette=Image.ADAPTIVE, colors=256)
        pil_frames.append(img)
    
    if pil_frames:
        duration = int(1000 / fps)
        pil_frames[0].save(
            output_path,
            save_all=True,
            append_images=pil_frames[1:],
            duration=duration,
            loop=0
        )


def save_as_video(frames: List[bytes], width: int, height: int,
                  output_path: Path, fps: int, audio_path: Optional[Path] = None) -> None:
    """Save frames as video using ffmpeg, optionally with audio."""
    with tempfile.TemporaryDirectory() as temp_dir:
        temp_path = Path(temp_dir)
        
        for i, frame_data in enumerate(frames):
            img = Image.frombytes("RGBA", (width, height), frame_data, "raw", "BGRa")
            img = img.convert("RGB")
            img.save(temp_path / f"frame_{i:06d}.png")
        
        cmd = [
            "ffmpeg", "-y",
            "-framerate", str(fps),
            "-i", str(temp_path / "frame_%06d.png"),
        ]
        
        # Add audio input if provided
        if audio_path and audio_path.exists():
            cmd.extend(["-i", str(audio_path)])
        
        cmd.extend([
            "-c:v", "libx264",
            "-pix_fmt", "yuv420p",
            "-crf", "18",
        ])
        
        # Add audio codec if audio is included
        if audio_path and audio_path.exists():
            cmd.extend([
                "-c:a", "aac",
                "-b:a", "128k",
                "-shortest",  # Match video length
            ])
        
        cmd.append(str(output_path))
        
        try:
            subprocess.run(cmd, check=True, capture_output=True)
        except subprocess.CalledProcessError as e:
            print(f"Error: ffmpeg failed: {e.stderr.decode()}")
            sys.exit(1)
        except FileNotFoundError:
            print("Error: ffmpeg not found. Please install ffmpeg.")
            sys.exit(1)


def main():
    parser = argparse.ArgumentParser(
        description="Convert Xournal++ recording to video/GIF"
    )
    parser.add_argument("input", type=Path, help="Input JSON recording file")
    parser.add_argument("output", type=Path, help="Output video/GIF file")
    parser.add_argument("--fps", type=int, default=30, help="Frames per second (default: 30)")
    parser.add_argument("--width", type=int, default=None, 
                       help="Output width (default: auto from page size)")
    parser.add_argument("--height", type=int, default=None, 
                       help="Output height (default: auto from page size)")
    parser.add_argument("--scale", type=float, default=2.0,
                       help="Scale factor for output (default: 2.0 for HD quality)")
    parser.add_argument("--image-dir", type=Path, default=None,
                       help="Directory containing images (default: <input>_images)")
    parser.add_argument("--no-cursor", action="store_true", help="Hide cursor in video")
    parser.add_argument("--pattern", choices=["plain", "dotted", "graph", "ruled"],
                       default="plain", help="Background pattern (default: plain)")
    parser.add_argument("--audio", action="store_true", 
                       help="Generate audio (pen/eraser sounds synced with speed)")
    
    args = parser.parse_args()
    
    if not args.input.exists():
        print(f"Error: Input file not found: {args.input}")
        sys.exit(1)
    
    # Load audio files from script directory (scratch.wav and tap.wav)
    script_dir = Path(__file__).parent
    load_audio_files(script_dir)
    
    with open(args.input) as f:
        recording = json.load(f)
    
    if args.image_dir:
        image_dir = args.image_dir
    else:
        image_dir = args.input.parent / (args.input.stem + "_images")
    
    print(f"Generating frames from {args.input}...")
    frames, width, height, first_event_time = generate_frames(
        recording, image_dir, args.width, args.height, args.fps,
        show_cursor=not args.no_cursor,
        bg_pattern=args.pattern,
        scale_factor=args.scale
    )
    
    print(f"Generated {len(frames)} frames")
    
    output_ext = args.output.suffix.lower()
    
    # Generate audio if requested
    audio_path = None
    if args.audio and output_ext in (".mp4", ".mkv", ".avi", ".mov"):
        if AUDIO_AVAILABLE:
            print("Generating audio track...")
            events = recording.get("events", [])
            duration_ms = recording.get("duration_ms", 1000)
            
            # Calculate actual duration used in video
            if events:
                last_event_time = events[-1].get("timestamp", duration_ms) + 500
            else:
                last_event_time = duration_ms
            adjusted_duration = last_event_time - first_event_time
            
            audio_data = create_audio_track(events, adjusted_duration, first_event_time)
            if audio_data:
                audio_path = args.input.parent / (args.input.stem + "_audio.wav")
                save_audio_wav(audio_data, audio_path)
                print(f"Audio saved to {audio_path}")
        else:
            print("Warning: numpy not installed, audio generation disabled")
            print("Install with: pip install numpy")
    
    if output_ext == ".gif":
        print(f"Saving as GIF: {args.output}")
        save_as_gif(frames, width, height, args.output, args.fps)
    elif output_ext in (".mp4", ".mkv", ".avi", ".mov"):
        print(f"Saving as video: {args.output}")
        save_as_video(frames, width, height, args.output, args.fps, audio_path)
    else:
        print(f"Error: Unsupported output format: {output_ext}")
        sys.exit(1)
    
    # Clean up temporary audio file
    if audio_path and audio_path.exists():
        try:
            os.remove(audio_path)
        except:
            pass
    
    print("Done!")


if __name__ == "__main__":
    main()
